version: '3.8'

services:
  glitchbox:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glitchbox
    # privileged: true
    # network_mode: "host"
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock 
    #   - /proc:/proc
    environment:
      - TZ=Asia/Ho_Chi_Minh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "blade", "version"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 